name: ghclient
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  mockito: ^5.4.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
